- name: node-build clone
  tags:
    - node
    - node/node-build
  become: true
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  git: >
    repo=https://github.com/nodenv/node-build.git
    dest={{ node_build__path }}

- name: node-build install
  tags:
    - node
    - node/node-build
  become: true
  ignore_errors: yes # install.sh内でのエラー抑制
  shell: |
    cd {{ node_build__path }}
    ./install.sh

- name: get node versions
  tags:
    - node
    - node/node-build
  become: true
  ignore_errors: yes # install.sh内でのエラー抑制
  environment:
    PATH: "{{ node__bin_path }}:{{ ansible_env.PATH }}"
  command: node-build --definitions
